### ISSUE TITLE
Please simplify policy generator

### ISSUE THREAD

**Issue by ravi2099** [cooperwalbrun/aws-iam-actions-support#1]
Please simplify policy generator where user can easily generate their policy. it is very difficult to understand for user to generate policy.

**Comment by cooperwalbrun** [comment]
What part specifically do you find difficult to understand?

**Comment by tvb** [comment]
@cooperwalbrun I guess it is maybe hard to think of an action if you don't know the service name to begin with. A filter on service with a nice overview would be a great addition.

**Comment by tvb** [comment]
Also a filter on showing only `write`, `read`, or `list` permissions would be nice

**Comment by cooperwalbrun** [comment]
>@cooperwalbrun I guess it is maybe hard to think of an action if you don't know the service name to begin with. A filter on service with a nice overview would be a great addition.

Can you be a little more specific about what you mean by "a nice overview"? I do not think it would be too difficult to have a dropdown for choosing the service, though if a user has to choose both a service and an action for each action insertion, it could result in a tedious amount of clicking. I would have to think about how to incorporate that into the interface in a user-friendly manner.

An alternative idea I had on this front is to simply include service name headers within the actions search dropdown, and furthermore make the service names themselves searchable. Here is an example to illustrate the idea:

Current behavior:
```
(user types "ec2" in the box)

Dropdown:

  cloud9:ActivateEC2Remote
  cloud9:CreateEnvironmentEC2
  cloud9:DescribeEC2Remote
  cloud9:ModifyTemporaryCredentialsOnEnvironmentEC2
  compute-optimizer:GetEC2InstanceRecommendations
  compute-optimizer:GetEC2RecommendationProjectedMetrics
  ec2-instance-connect:OpenTunnel
  ...other results omitted for brevity
```

My idea:
```
(user types "ec2", "amazon ec2", or similar in the box)

Dropdown:

  AWS Cloud9
    cloud9:ActivateEC2Remote
    cloud9:CreateEnvironmentEC2
    cloud9:DescribeEC2Remote
    cloud9:ModifyTemporaryCredentialsOnEnvironmentEC2
  AWS Compute Optimizer
    compute-optimizer:GetEC2InstanceRecommendations
    compute-optimizer:GetEC2RecommendationProjectedMetrics
  Amazon EC2 Instance Connect
    ec2-instance-connect:OpenTunnel
  ...other results omitted for brevity
```

---

>Also a filter on showing only `write`, `read`, or `list` permissions would be nice

This would be a bit easier to implement. I could add a checkbox for each action type that should show up in the search results at any given time, and default all of them to a toggled state. I will have to ask around whether this kind of change would be worth the additional interface complexity.

**Comment by tvb** [comment]
@cooperwalbrun Let's start with your suggestion indeed, it sounds like a helpful improved for sure.

The reason for filtering on write, read, or list permissions would be helpful if one is only looking for ReadOnly type of permissions to put in IAM Boundaries or specific SCPs.

**Comment by cooperwalbrun** [comment]
The changes discussed above have been implemented.
