### ISSUE TITLE
Missing a RSS feed

### ISSUE THREAD

**Issue by tvb** [cooperwalbrun/aws-iam-actions-support#2]
Hi!

I love your site, the one thing missing is a RSS feed for the changelog. I would like to integrate the feed into Slack to get notified upon any changes.

Could you add this please?

**Comment by cooperwalbrun** [comment]
Hey, thanks for the feedback. I created a basic RSS feed at https://www.awsiamactions.io/rss if you want to check it out. I also added a link to it on https://www.awsiamactions.io/changelog.

**Comment by cooperwalbrun** [comment]
One of my peers added the new RSS feed to a Slack channel and it appears to be working as expected (today's changes were published correctly), so I am going to close this issue. Let me know if you have any problems on your end.

**Comment by tvb** [comment]
@cooperwalbrun Awesome! Works as intended 🤩
