### ISSUE TITLE
Please add a link to copy to the changelog overview

### ISSUE THREAD

**Issue by tvb** [cooperwalbrun/aws-iam-actions-support#4]
Hi,

Maybe another feature which might be helpful is a link to the individual changelog items. It would make it way more convenient to point teams directly to a changelog item.

**Comment by cooperwalbrun** [comment]
Hi. I added a `Copy Link` button to each changelog entry to make it easier to acquire a "direct link" to the it. Let me know what you think.

**Comment by cooperwalbrun** [comment]
Hey. I added a `Copy Link` button to each changelog entry to make it easier to acquire a "direct link" to it. Let me know what you think.

**Comment by tvb** [comment]
That was quick to respond! Other than styling (I prefer the "link" icon) I guess it works perfectly. Thanks @cooperwalbrun
