### ISSUE TITLE
Rss and changelog broken?

### ISSUE THREAD

**Issue by tvb** [cooperwalbrun/aws-iam-actions-support#5]
Hi,

I noticed the changelog has not been updated since 11-17th. Also, the RSS feed seems broken.

Can you have a look? And perhaps add some monitoring.

**Comment by cooperwalbrun** [comment]
Everything is working properly. AWS has not added or removed any actions since 2023-11-17. The reason the RSS feed is empty is because it only retains the past 14 days' worth of changes.

**Comment by cooperwalbrun** [comment]
Following up on this for transparency: there were no issues at the time of my comment above, however, a large number of changes were introduced during the day on 2023-12-01, and these changes caused the daily rebuild process to break on 2023-12-02 and 2023-12-03. I have just now fixed the issue and rebuilt the site with the latest changes.
