### ISSUE TITLE
Search results hidden is not helpful

### ISSUE THREAD

**Issue by tvb** [cooperwalbrun/aws-iam-actions-support#6]
Hi! 

I got another request. The _x more results hidden_ is actually not helpful. Now, I cannot see in a glance which permissions I am missing. Even if I use the filters, not all permissions are shown at once. I propose to make it clickable to load more.

![Scherm­afbeelding 2024-01-09 om 09 43 50](https://github.com/cooperwalbrun/aws-iam-actions-support/assets/1263414/4e3b266b-6405-40a4-810e-40729852fa9c)

**Comment by cooperwalbrun** [comment]
I have implemented a change to include a `Load 10 More` button below the results.

**Comment by tvb** [comment]
🤩
