### ISSUE TITLE
Is it possible to download JSON programmatically

### ISSUE THREAD

**Issue by moltar** [cooperwalbrun/aws-iam-actions-support#7]
I know there's a "Save As" button, but it's only available from the browser.

What I'd like to do is to fetch the raw JSON file, and then codegen some TypeScript files from that.

Would it be possible to publish the raw JSON file?

Thanks!

**Comment by cooperwalbrun** [comment]
I will look around a bit and see if there are any shortcuts I can take to implement this, but it is likely not something that I could make available without a larger redesign and/or major release due to the scope of the changes required to make it possible.

**Comment by moltar** [comment]
Is it possible to contribute?

**Comment by mycarrysun** [comment]
Would love to use this to codegen a terraform module too - it would be super helpful to have autocompleted constants instead of a bunch of magic strings everywhere in all your policies

**Comment by mycarrysun** [comment]
I just published a terraform module with the json from your website - hope you don't mind :sweat_smile: 

https://registry.terraform.io/modules/mycarrysun/policy-actions/aws

I cannot believe there has not been a module published like this yet.

**Comment by moltar** [comment]
I've added a repo to automate the export using Playwright:

https://github.com/moltar/export-awsiamactions?tab=readme-ov-file#export-of-awsiamactionsio

**Comment by cooperwalbrun** [comment]
I finally figured out how to implement this. There is now an endpoint available with the (raw) JSON data at [www.awsiamactions.io/json](https://www.awsiamactions.io/json). This is also mentioned/linked near the bottom of the homepage.

Due to the size of this data, it could end up being financially costly for me to serve this endpoint, so I may have to make further adjustments depending on what the traffic looks like.

**Comment by moltar** [comment]
lol wasted half a sunday on my scraper solution 😅

**Comment by moltar** [comment]
> Due to the size of this data, it could end up being financially costly for me to serve this endpoint

Could you perhaps proxy it with Cloudflare?

**Comment by cooperwalbrun** [comment]
I am already proxying it with a CDN. I am going to be tinkering with some caching settings to try to optimize, but for the purposes of this issue, the feature should be implemented as requested.

**Comment by moltar** [comment]
Thank you! 👍🏼

**Comment by vincenthsh** [comment]
@moltar  / @mycarrysun -what's the difference between just using https://iam-floyd.readthedocs.io/en/v0.650.0/ (which works really well with both aws-cdk and cdktf) and using this json or tf-module from Mike

**Comment by moltar** [comment]
1. I only want action names 
2. I don't like the builder pattern 
3. I don't like the name

**Comment by vincenthsh** [comment]
aside from the name, very valid points - thanks!

**Comment by moltar** [comment]
All points are valid, because they are my opinions. You may disagree but it does not invalidate my opinions.

My opinion is that package names, especially when it comes to security, in highly regulated environments, should not have obscure names. And should be as descriptive as possible.
