### ISSUE TITLE
Details on IAM Action scraping and generation

### ISSUE THREAD

**Issue by vincenthsh** [cooperwalbrun/aws-iam-actions-support#8]
I'm curious how the iam actions data is maintained (specifically guaranteed accuracy). I've been using a similar framework which has a clear statement how the data is generated and was wondering how this website compares.

See:
https://github.com/udondan/iam-floyd?tab=readme-ov-file#legal

**Comment by cooperwalbrun** [comment]
The main difference in the data availability/accuracy of this project compared to the one you linked seems to be the update cadence: `iam-floyd` appears to have an ad-hoc release schedule, whereas AWS IAM Actions updates every day. `iam-floyd`'s release schedule is speculation on my part based on the changelog [here](https://github.com/udondan/iam-floyd/commits/main/CHANGELOG), which sometimes updates on consecutive days and other times goes multiple weeks without any updates at all.

**Comment by vincenthsh** [comment]
just curious if it makes sense to have a similar disclaimer on data accuracy?
